version: '3'
services:
  backend:
    build: ./src
    ports: 
      - 5000:5000
    networks: 
      - backbone

  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx-app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - backbone

networks: 
  backbone:
    driver: bridge
